# Site settings
title: کتابخانه باشگاه کوهنوردی شقایق
#email: shaghayeghclub1992@gmail.com
#description: >
#  Write an awesome description for your new site here. You can edit this
#  line in _config.yml. It will appear in your document head meta (for
#  Google search results) and in your feed.xml site description.
# baseurl: ""
# url: "http://lib.shaghayeghclub1992.com"


# Collections
# collections:
#   books:
#     output: false

sass:
  style: compressed



# Tracker
analytics: G-KPMCPV2WFD


#collection
#collections:
 # projects:
  #  output: true
   # permalink: /projects/:path/



#include:
 # - _pages




plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-email-protect
  - jekyll-target-blank
